package com.example.thindie.core.localrawresources.parserules

internal const val COORDINATES_PATTERN_WITH_POINT = "^\\d{2,3}.\\d{2,}\\s{1,}\\d{2,3}.\\d{2,}"
internal const val CITY = "city"
internal const val SPLIT_BY_WHITESPACE = " "
internal const val LATITUDE = "lat"
internal const val LONGITUDE = "lng"
internal const val FAKE_TIME_ZONES = "Europe/Moscow"

internal val singleSymbolMapTranscrypt = mapOf(
    "a" to "а",
    "b" to "б",
    "v" to "в",
    "g" to "г",
    "d" to "д",
    "e" to "е",
    "z" to "з",
    "i" to "и",
    "j" to "й",
    "k" to "к",
    "l" to "л",
    "m" to "м",
    "n" to "н",
    "o" to "о",
    "p" to "п",
    "r" to "р",
    "s" to "с",
    "t" to "т",
    "u" to "у",
    "f" to "ф",
    "c" to "ц",
    "y" to "й",
    "’" to "ь",
    "’’" to "ъ",

    )
internal val fewSymbolsMapTranscryptions = mapOf(
    "/" to " ",
    "Moscow" to "Москва",
    "Saint Petersburg" to "Санкт-Петербург",
    "Europe" to "Европа",
    "Sovetsk" to "Советск",
    "Astrakhan" to "Астрахань",
    "Kazan" to "Казань",
    "nyye" to "ные",
    "Tver" to "Тверь",
    "airport" to "Аэропорт",
    "Arkhangelsk" to "Архангельск",
    "house" to "хаус",
    "cottage" to "коттэдж",
    "tower" to "тауэр",
    "building" to "билдинг",
    "station" to "станция",
    "Podolsk" to "Подольск",
    "Asia" to "Азия",
    "ishche" to "ище",
    "niye" to "ние",
    "Yosh" to "Йош",
    "Shchel" to "Щёл",
    "ntsyn" to "нцын",
    "Nalchik" to "Нальчик",
    "Engels" to "Энгельс",
    "atsk" to "атск",
    "etsk" to "ецк",
    "ryan" to "рян",
    "zhniy" to "жний",
    "nyy" to "ный",
    "chyor" to "чёр",
    "cher" to "чер",
    "ol’" to "оль",
    "al’" to "аль",
    "el’" to "ель",
    "il’" to "иль",
    "yany" to "яны",
    "ayo" to "айо",
    "еschе" to "еще",
    "nts" to "нц",
    "siy" to "сий",
    "yu" to "ю",
    "ye" to "е",
    "ya" to "я",
    "tsk" to "цк",
    "ets" to "ец",
    "iy" to "ий",
    " ts" to " Це",
    "ry" to "ры",
    "vy" to "вы",
    "zy" to "зы",
    "ty" to "ты",
    "khy" to "хи",
    "hy" to "хы",
    "ly" to "лы",
    "gy" to "гы",
    "dy" to "ды",
    "fy" to "фы",
    "my" to "мы",
    "by" to "бы",
    "cy" to "цы",
    "kh" to "х",
    "ch" to "ч", //
    "sh" to "ш", //
    "sh'" to "щ", //
    "yo" to "ё",
    "zh" to "ж",

    //
)