package com.example.jazzyweather.domain

data class Weather(
    val place: String,
    val latitude: Float,
    val longitude: Float,
    val temperature: Double,
    val time: String,
    val weathercode: Int,
    val winddirection: Double,
    val windspeed: Double,
    val apparentTemperatureMax: List<Double>,
    val apparentTemperatureMin: List<Double>,
    val precipitationSum: List<Double>,
    val rainSum: List<Double>,
    val showersSum: List<Double>,
    val snowfallSum: List<Double>,
    val sunrise: List<String>,
    val sunset: List<String>,
    val temperatureMax: List<Double>,
    val temperatureMin: List<Double>,
    val times: List<String>,
    val weatherCodes: List<Int>,
    val windgusts10mMax: List<Double>,
    val windspeed10mMax: List<Double>,
    val isPlus: Boolean = temperature > 0.00,
)